clone_folder: c:\trik-desktop-gamepad

environment:
  global:
    PROJECT_FILE: trikDesktopGamepad 

  matrix:
      - MINGW: C:\Qt\Tools\mingw730_32
        QTDIR: C:\Qt\5.12\mingw73_32

configuration:
  - debug
  - release

#cache:
#  - '%BUILD_DIR%'
before_build:
  - git submodule update --init --recursive
  - set PATH=%PYTHON_PATH%;%QTDIR%\bin;%MINGW%\bin;C:\msys64\usr\bin;%PATH%
  - path
  - python -V
  - qmake -v
  - g++ --version

build_script:
  - qmake %APPVEYOR_BUILD_FOLDER%\%PROJECT_FILE%.pro CONFIG+=%CONFIGURATION%
  - mingw32-make -j2 qmake_all
  - mingw32-make -j2 all
